### ISSUE TITLE
영어 대소문자, 그리고 공백 ' ' 으로 구성된 문자열이 있다. 마지막 단어의 길이를 구하라. 단어가 없으면 0을 리턴하라.

### ISSUE THREAD

**Issue by minnamgoong** [algorithm-study-of-GN/problem-of-coding-interview#11]

**Comment by SeongUgJung** [comment]
스터디 # 2 완료
@minnamgoong 님이 별도로 해답을 올려주시기로 하셨습니다.

**Comment by minnamgoong** [comment]
http://www.programcreek.com/2014/05/leetcode-length-of-last-word-java/

Given a string s consists of upper/lower-case alphabets and empty space characters ' ', return the length of last word in the string. If the last word does not exist, return 0.

Java Solution

Very simple question. We just need a flag to mark the start of letters from the end. If a letter starts and the next character is not a letter, return the length.

public int lengthOfLastWord(String s) { 
    if(s==null || s.length() == 0)
        return 0;

```
int result = 0;
int len = s.length();

boolean flag = false;
for(int i=len-1; i>=0; i--){
    char c = s.charAt(i);
    if((c>='a' && c<='z') || (c>='A' && c<='Z')){
        flag = true;
        result++;
    }else{
        if(flag)
            return result;
    }
}

return result;}
```
