### ISSUE TITLE
Stack - p99

### ISSUE THREAD

**Issue by mycisco** [algorithm-study-of-GN/problem-of-coding-interview#22]

**Comment by minnamgoong** [comment]
다른 자료구조를 사용하지 않고, 고정 크기의 배열 1개만 이용하여 1개의 스택을 구현하라.

pop()
push()

https://www.cs.bu.edu/teaching/c/stack/array/
find "Implementing a stack with an array"

http://www.c4learn.com/c-programs/c-program-to-implement-stack-operations-using-array.html
