### ISSUE TITLE
단일 연결 리스트가 cyclic 인지 아닌지를 확인하라.

### ISSUE THREAD

**Issue by minnamgoong** [algorithm-study-of-GN/problem-of-coding-interview#24]
http://www.programmerinterview.com/index.php/data-structures/how-to-find-if-a-linked-list-is-circular-or-has-a-cycle-or-it-ends/
- value, next 2개의 property만 있는 단일 연결 리스트에서, 순환하는 구간이 있는지 (cyclic) 아닌지를 검사하라.

**Comment by SeongUgJung** [comment]
7/17 해결
