### ISSUE TITLE
이진수의 숫자 1 과 다음 숫자 1 의 거리가 가장 먼 길이를 구하라.

### ISSUE THREAD

**Issue by coffeenjava** [algorithm-study-of-GN/problem-of-coding-interview#26]
양수 int(10진수)를 이진수로 변환하였을 때 1 과 1 사이의 gap이 가장 큰 값을 구하라.
예)
9(int 10진수) -> 1001 => 결과 2
529 -> 1000010001 => 4
20 -> 10100 => 1
15 -> 1111 => 0 (gap 이 없을 경우 0 return)

**Comment by SeongUgJung** [comment]
7/17 해결
