### ISSUE TITLE
1.7 번문제 (p93)

### ISSUE THREAD

**Issue by SeongUgJung** [algorithm-study-of-GN/problem-of-coding-interview#3]
MxN 행렬을 순회하면서 0인 원소를 발견하면 해당원소에 속하 행과열을 모두 0으로 만들어라

**Comment by eunice-yu** [comment]
MxN  행렬을 순회하면서 0인 원소를 발견하면 해당원소에 속하 행과열을 모두 0으로 만들어라

**Comment by SeongUgJung** [comment]
@minnamgoong 시험
