### ISSUE TITLE
9.1번 문제 (p109)

### ISSUE THREAD

**Issue by mycisco** [algorithm-study-of-GN/problem-of-coding-interview#4]
Interview Questions

A child is running up a staircase with n steps, and can hop either 1 step, 2 steps, or 3 steps at a time. Implement a method to count how many possible ways the child can run up the stairs.

n개의 계단을 아이가 오른다. 한 번에 1계단 오르기도 하고, 2계단이나 3계단씩 오르기도 한다. 계단을 오르는 데 몇 가지 방법이 있는 계산하는 메서드를 구현하라.

**Comment by SeongUgJung** [comment]
7/24 처리

**Comment by minnamgoong** [comment]
A.

n번째 계단에 도달하는 방법을 생각해보자.
n-1 번째 계단에서 1 계단 더 올라 n번째 계단에 도달하는 경우
n-2 번째 계단에서 2 계단 더 올라 n번째 계단에 도달하는 경우
n-3 번째 계단에서 3 계단 더 올라 n번째 계단에 도달하는 경우 가 있을 수 있다.

마지막 계단에 오르는 방법의 가짓수는 그 전 세 계단에 도착하는 경우의 수를 모두 더한것이다.

public int countWays(int n) {
    if (n < 0) { // 남은 계단이 없으면, 올라가는 방법은 0 가지.
        return 0;
    } else if (n == 0) {
        return 1; // 남은 계단이 1개면, 올라가는 방법은 1가지 (1계단 올라가는것)
    } else {
        return countWays(n - 1) + countWays(n - 2) + countWays(n - 3);
        // 그게 아니라면 1계단, 2계단, 3계단 더 올라가는 경우의 수의 합.
    }
}
