### ISSUE TITLE
3.6번 문제 (p102)

### ISSUE THREAD

**Issue by xaliver** [algorithm-study-of-GN/problem-of-coding-interview#9]
큰값이 위에 오도록 stack을 오름차순으로 정렬
여벌 stack하나를 더 사용할 수 있고 스택 요소들을 배열이나 다른 자료구조에 복사할 수 없음
Stack 제공함수 push pop peek isEmpty

**Comment by gripjun** [comment]
스터디 3에서 완료
2016. 7. 3(일)

실습 코드 업로드한 것입니다.
[https://github.com/algorithm-study-of-GN/problem-of-coding-interview/blob/master/prob_3.6_issue_9/SortStack/SortStack.java](url)

**Comment by minnamgoong** [comment]
import org.junit.Test;
import java.util.Stack;
import static org.junit.Assert.*;

/**
- To work on unit tests, switch the Test Artifact in the Build Variants view.
  */
  public class ExampleUnitTest {
  @Test
  public void sortStack() {
      Stack<Integer> s = new Stack<>();
      s.push(9);
      s.push(3);
      s.push(11);
      s.push(6);
  
  ```
  Stack<Integer> result = sort(s);
  System.out.println(result);
  ```
  
  }
  
  public static Stack<Integer> sort(Stack<Integer> s) {
      Stack<Integer> r = new Stack<>();
      while (!s.isEmpty()) {
          int tmp = s.pop();
          while (!r.isEmpty() && r.peek() > tmp) {
              s.push(r.pop());
          }
          r.push(tmp);
          System.out.print("s: " + s);
          System.out.println(", r: " + r);
      }
      return r;
  }
  }
